#!/bin/sh

/usr/bin/vim -n \
 -T "xterm" \
 -c "syntax on" \
 -c ":let html_no_pre = 1" \
 -c ":let use_xhtml = 1" \
 -c ":let html_use_css = 1" \
 -c ":so /usr/share/vim/vim80/syntax/2html.vim" \
 -c "%s/<C-k>6'\|<C-k>9'/'/g" \
 -c ":w $2" \
 -c ':q!' \
 -c ':q!' \
 "$1"
